services:
  db_glpi:
    image: mariadb:10.11
    container_name: glpi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipass
    volumes:
      - ../glpi_db_data:/var/lib/mysql

  glpi:
    image: glpi/glpi
    container_name: glpi_app
    restart: unless-stopped
    depends_on:
      - db_glpi
    environment:
      GLPI_INSTALL_AUTO: "1"
      GLPI_DB_HOST: db_glpi
      GLPI_DB_NAME: glpidb
      GLPI_DB_USER: glpi
      GLPI_DB_PASSWORD: glpipass
    ports:
      - "80:80"
    volumes:
      - ../glpi_data:/var/www/html